// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdcys_A0RZ6tRr3lag0opkQ4QGonUjaG4',
    appId: '1:53974988700:web:5d90bd704e1290878c3a59',
    messagingSenderId: '53974988700',
    projectId: 'wonderwedding-aa6c3',
    authDomain: 'wonderwedding-aa6c3.firebaseapp.com',
    storageBucket: 'wonderwedding-aa6c3.firebasestorage.app',
    measurementId: 'G-VK8V2PZ10V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1HHk-3iMpdk_3Dprc8gdT1cPboBI0xZI',
    appId: '1:53974988700:android:b1a96fb260b3ac228c3a59',
    messagingSenderId: '53974988700',
    projectId: 'wonderwedding-aa6c3',
    storageBucket: 'wonderwedding-aa6c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAq5yEXlWijXbrsfXRTC8vPUFsKTSfvbw',
    appId: '1:53974988700:ios:b694d41fb55434288c3a59',
    messagingSenderId: '53974988700',
    projectId: 'wonderwedding-aa6c3',
    storageBucket: 'wonderwedding-aa6c3.firebasestorage.app',
    androidClientId: '53974988700-2d1cqnb7k0t3kjq6dkfuhrf225hpcoh9.apps.googleusercontent.com',
    iosClientId: '53974988700-t6g8hdim7dvgm8o4t4mle1bfommdshjs.apps.googleusercontent.com',
    iosBundleId: 'com.example.wonderclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAq5yEXlWijXbrsfXRTC8vPUFsKTSfvbw',
    appId: '1:53974988700:ios:b694d41fb55434288c3a59',
    messagingSenderId: '53974988700',
    projectId: 'wonderwedding-aa6c3',
    storageBucket: 'wonderwedding-aa6c3.firebasestorage.app',
    androidClientId: '53974988700-2d1cqnb7k0t3kjq6dkfuhrf225hpcoh9.apps.googleusercontent.com',
    iosClientId: '53974988700-t6g8hdim7dvgm8o4t4mle1bfommdshjs.apps.googleusercontent.com',
    iosBundleId: 'com.example.wonderclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdcys_A0RZ6tRr3lag0opkQ4QGonUjaG4',
    appId: '1:53974988700:web:009607c67256abcf8c3a59',
    messagingSenderId: '53974988700',
    projectId: 'wonderwedding-aa6c3',
    authDomain: 'wonderwedding-aa6c3.firebaseapp.com',
    storageBucket: 'wonderwedding-aa6c3.firebasestorage.app',
    measurementId: 'G-WR2Z4RV2HF',
  );
}
